In [1]:
import numpy as np 

In [3]:
#array creation
a = np.array([1,2,3,4])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [4]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [5]:
#Transpose
b.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [6]:
#Dot Product
print(np.dot(b,b.T))

[[ 30  70]
 [ 70 174]]


In [7]:
#Making an array of random numbers
c = np.random.randint(50,100,10)
print(c)

[75 85 94 83 63 98 77 65 58 57]


In [9]:
d = np.random.randint(1,50,(5,5))
print(d)

[[16 21 13  2 28]
 [20  4 11 49 18]
 [23 37  5 30 47]
 [ 6 32  1  3 21]
 [31 41 37 17 12]]


In [11]:
# min/ max values
print(np.max(d))
print(np.min(d))
print(np.max(a))

49
1
4


In [12]:
#unique values in array
e = np.array([1,0,2,2,3,1,3,2,2,0,1,3])
np.unique(e)

array([0, 1, 2, 3])

In [13]:
f = np.unique(e, return_counts=True)
print(f)

(array([0, 1, 2, 3]), array([2, 3, 4, 3]))


In [16]:
print(f[0])
print(f[1])

[0 1 2 3]
[2 3 4 3]


In [17]:
#finding element with max freq
index = np.argmax(f[1])
element = f[0][index]
print(element)

2


In [23]:
#Slicing
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print(matrix[1:3,0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5]
 [7 8]]


In [24]:
#indexing is normal
matrix[1][1]

5

In [34]:
#Working with Matrices
a = np.zeros((3,3))
print(a)
b =np.ones((3,3))
print(b)
#reassignment
b[1,:] = 5
b[:,-1] = 6 #last row or col can be indexed as -1
print(b)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 6.]
 [5. 5. 6.]
 [1. 1. 6.]]


dtype('float64')

In [32]:
c=np.full((3,2),5)
print(c)
#identity matrix
d = np.eye((4))
print(d)

[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [33]:
#random matrix generation 
random_matrix = np.random.random((3,2))
random_matrix

array([[0.41902663, 0.96710692],
       [0.10428333, 0.39680794],
       [0.85377773, 0.9250285 ]])

In [37]:
#Operations on Matrix
x = np.array([[1,2],[5,6]])
y = np.array([[3,4],[7,8]])
print(x+y)
print(np.add(x,y))

[[ 4  6]
 [12 14]]
[[ 4  6]
 [12 14]]


In [38]:
print(x-y)
print(np.subtract(x,y))
print(x*y)
print(np.multiply(x,y)) #element wise multiplication, not matrix multilication 

[[-2 -2]
 [-2 -2]]
[[-2 -2]
 [-2 -2]]
[[ 3  8]
 [35 48]]
[[ 3  8]
 [35 48]]


In [39]:
#element wise division
print(x/y)
np.divide(x,y)

[[0.33333333 0.5       ]
 [0.71428571 0.75      ]]


array([[0.33333333, 0.5       ],
       [0.71428571, 0.75      ]])

In [47]:
#MATRIX MULTIPLICATION
print(x.dot(y))
print(np.dot(x,y))
print(x)
print(np.sum(x))
print(np.sum(x, axis=0)) #sum along columns
print(np.sum(x, axis=1)) #sum along rows

[[17 20]
 [57 68]]
[[17 20]
 [57 68]]
[[1 2]
 [5 6]]
14
[6 8]
[ 3 11]


In [44]:
#multiplication of vectors
m = np.array([1,2,3,4])
n = np.array([5,6,7,8])
print(m.dot(n))
print(sum(n))

70
26


In [52]:
#Stacking of arrays
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
b=b**2
print(b)

[25 36 49 64]


In [53]:
np.stack((a,b), axis=0)
#stacking vertically

array([[ 1,  2,  3,  4],
       [25, 36, 49, 64]])

In [55]:
c = np.stack((a,b), axis=1)
print(c)
#stacking horizontally, side by side

[[ 1 25]
 [ 2 36]
 [ 3 49]
 [ 4 64]]


In [56]:
c = c.reshape((2,4)) #reshaping

In [57]:
c

array([[ 1, 25,  2, 36],
       [ 3, 49,  4, 64]])

In [60]:
d = c.reshape((8,1))
d

array([[ 1],
       [25],
       [ 2],
       [36],
       [ 3],
       [49],
       [ 4],
       [64]])

In [64]:
e=c.reshape((2,-1)) #automatically picks up other dimension, if possible
f=c.reshape((-1,1))
print(e)
print(f)

[[ 1 25  2 36]
 [ 3 49  4 64]]
[[ 1]
 [25]
 [ 2]
 [36]
 [ 3]
 [49]
 [ 4]
 [64]]


In [71]:
#RANDOM GENERATORS IN NUMPY
#1 List from range
a = np.arange(20)
print(a)
a = a+5
print(a)
np.random.shuffle(a) #shuffles the contents of a sequence
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[20 10 13  6 22 24 11  7  9 12 18 17 14 23 15 16  5 19 21  8]


In [74]:
#2 Usinf rand/ random
p = np.random.random((3,2))
print(p)
r = np.random.rand(3,4)
print(r)

[[0.95034194 0.64071353]
 [0.19527966 0.81378303]
 [0.54128311 0.5056348 ]]
[[0.78681498 0.27170617 0.60330704 0.14531379]
 [0.16168206 0.52788013 0.24863431 0.12044491]
 [0.17964407 0.74376571 0.19166728 0.2815582 ]]


In [76]:
#3 Random values that form a std normal deviation
c = np.random.randn(2,2)
c

array([[-0.48583234, -0.79817114],
       [-0.12679422,  0.10759252]])

In [77]:
#4 List/array of random numbers, from given range, say (1,100)
d = np.random.randint(1,100,15)
d

array([89, 91, 24, 92, 49, 38,  4, 89, 27, 11, 90, 12, 83,  5, 16])

In [79]:
#5 Selecting a random value from a sequence
elt = np.random.choice([1,2,3,4,5,6,7,8,9,10])
elt

1

In [80]:
#to generate the same random values every time your code is run, give some constant seed value
#eg: np.random.seed(1)

In [82]:
#STATISTICAL COMPUTATION USING NUMPY
p = np.array([[1,2,3,4],[5,6,7,8]])
print(np.min(p), np.max(p), np.min(p, axis=0), np.min(p, axis=1))

1 8 [1 2 3 4] [1 5]


In [84]:
#Mean
q=np.array([1,2,3,4,5])
m = sum(q)/5
print(m)
print(np.mean(q))
print(np.mean(p, axis=0), np.mean(p, axis=1))

3.0
3.0
[3. 4. 5. 6.] [2.5 6.5]


In [85]:
#Median
c = np.array([1,2,3,5,5,6,6,6,7])
print(np.median(c))

5.0


In [86]:
#Weighted average
w = np.array([1,2,3,4,5])
a = np.array([1,2,3,4,5])
print(np.mean(a))
print(np.average(a, weights=w))

3.0
3.6666666666666665


In [87]:
#Std Deviation/ Variance
u = np.mean(a)
myStd = np.sqrt(np.mean(abs(u-a)**2)) #manually calculating std dev
myStd

1.4142135623730951

In [88]:
std = np.std(a) #using fn
std

1.4142135623730951

In [90]:
#variance
print(std**2)
v=np.var(a) #using fn
v

2.0000000000000004


2.0

In [ ]:
#end